image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: portail-node

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    # - docker tag $IMAGE_NAME registry.gitlab.com/your-namespace/your-project:$CI_COMMIT_SHORT_SHA
    # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # - docker push registry.gitlab.com/your-namespace/your-project:$CI_COMMIT_SHORT_SHA
  only:
    - main
    - master

# deploy:
#   stage: deploy
#   script:
#     - echo "Déploiement ici (ex: ssh, kubectl, etc.)"
#   only:
#     - main
#     - master
