services:
  portail-node:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - node_modules_data:/app/node_modules
      - ./app:/app
    environment:
      - NODE_ENV=production
    command: node app.js

volumes:
  node_modules_data:
